// Generated by CoffeeScript 1.6.3
/*
 # Module dependencies.
*/


(function() {
  var api, app, express, http, mongoose, path, routes;

  console.log("fire app.js");

  express = require('express');

  routes = require('./routes');

  http = require('http');

  api = require('./routes/api');

  path = require('path');

  mongoose = require('mongoose');

  app = express();

  app.set('port', process.env.PORT || 3002);

  app.set('views', __dirname + '/../views');

  app.set('view engine', 'jade');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, '/../public')));

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  app.get('/', routes.layout);

  app.get('/partials/:name', routes.partials);

  app.get('/api/names', api.names);

  http.createServer(app).listen(app.get('port'), function() {
    console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);
