// Generated by CoffeeScript 1.6.3
/*
 # Module dependencies.
*/


(function() {
  var TestModel, app, express, http, mongoURI, mongoose, path, routes;

  console.log("fire app.js");

  express = require('express');

  routes = require('./routes');

  http = require('http');

  path = require('path');

  mongoose = require('mongoose');

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.set('views', __dirname + '/../views');

  app.set('view engine', 'jade');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, '/../public')));

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  mongoURI = process.env.MONGOHQ_URL || 'mongodb://localhost/veganizzmapp';

  mongoose.connect(mongoURI);

  TestModel = mongoose.model('TestModel', {
    name: String
  });

  app.get('/', routes.index);

  app.get('/charts', routes.charts);

  app.post('/submitdata', function(req, res) {
    var submitedInfo, testModel;
    submitedInfo = req.body;
    console.log("submitedInfo", submitedInfo);
    testModel = new TestModel(submitedInfo);
    testModel.save(function(err, data) {
      console.log("sent to database:", data);
    });
  });

  http.createServer(app).listen(app.get('port'), function() {
    console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);
