// Generated by CoffeeScript 1.6.3
/*
 # Serve JSON to our AngularJS client
*/


(function() {
  exports.names = function(req, res) {
    return res.json({
      names: [
        {
          name: 'Brian',
          city: 'Minneapolis'
        }, {
          name: 'Chase',
          city: 'Madison'
        }, {
          name: 'Collin',
          city: 'Boulder'
        }, {
          name: 'Brian',
          city: 'Boulder'
        }
      ]
    });
  };

}).call(this);
