// Generated by CoffeeScript 1.6.3
(function() {
  console.log("fire index.js");

  /*
   # GET home page.
  */


  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Cabin Manager'
    });
  };

  exports.partials = function(req, res) {
    var name;
    name = req.params.name;
    return res.render('partials/' + name);
  };

}).call(this);
