// Generated by CoffeeScript 1.6.3
(function() {
  console.log("fire index.js");

  module.exports = {
    index: function(req, res) {
      res.render('index', {
        title: 'Cabin Manager'
      });
    },
    charts: function(req, res) {
      res.render('charts.jade', {
        title: 'Cabin Manager',
        subtitle: 'Charts'
      });
    },
    forms: function(req, res) {
      res.render('forms.jade', {
        title: 'Cabin Manager',
        subtitle: 'Forms'
      });
    },
    calendar: function(req, res) {
      res.render('calendar.jade', {
        title: 'Cabin Manager',
        subtitle: 'Calendar'
      });
    },
    contacts: function(req, res) {
      res.render('contacts.jade', {
        title: 'Cabin Manager',
        subtitle: 'Contacts'
      });
    },
    tables: function(req, res) {
      res.render('tables.jade', {
        title: 'Cabin Manager',
        subtitle: 'Tables'
      });
    }
  };

}).call(this);
