// Generated by CoffeeScript 1.6.3
(function() {
  console.log("fire index.js");

  /*
   # GET home page.
  */


  module.exports = {
    layout: function(req, res) {
      return res.render('layout', {
        title: 'Cabin Manager'
      });
    },
    partials: function(req, res) {
      var name;
      name = req.params.name;
      return res.render('partials/' + name);
    }
  };

}).call(this);
